name: Build NGINX Image
on:
  workflow_dispatch:
#  push:
#    branches:
#      - main

jobs:
  Docker-build:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set Up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Version
        id: get_version
        run: |
          repo="Akimio521/AutoFilm"
          latest=$(curl -s https://api.github.com/repos/$repo/releases/latest)
          version=$(echo $latest | jq -r '.tag_name')
          echo "REPO=$repo" >> $GITHUB_ENV
          echo "VER1=$version" >> $GITHUB_ENV
          echo "VER2=${version#v}" >> $GITHUB_ENV

      - name: Build and Push
        run: |
          cd nginx
          sh prepare.sh
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/autofilm:${{ env.VER2 }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/autofilm:latest \
            -f Dockerfile . --push