name: Build Docker Image

on:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'GitCourser/docker'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set Up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        run: |
          cd $imagename
          docker buildx build --platform linux/amd64,linux/arm64 -t $username/$imagename:latest -f Dockerfile . --push
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          imagename: py-browser