name: Docker

on:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'GitCourser/docker'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          cd amd64
          wget https://registry.npmmirror.com/-/binary/electron/12.1.0/electron-v12.1.0-linux-x64.zip
          mkdir electron
          unzip electron-v12.1.0-linux-x64.zip -d electron
          wget -P electron https://github.com/electron/electron/raw/main/default_app/icon.png
          DOCKER_BUILDKIT=1 docker build --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg ARG_APT_NO_RECOMMENDS=1 -t ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu:amd64 .
          docker images

      - name: Push to Docker Repository
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu:amd64
