name: Docker Hub Free

on:
  schedule:
    - cron: '0 0 1 */2 *'  # 每两月
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'GitCourser/docker'
    steps:
      - name: keep the activity
        env:
          user: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker pull -a "$user"/nginx
          docker pull -a "$user"/ubuntu
          docker pull -a "$user"/electron
          docker pull -a "$user"/edge
          docker pull -a "$user"/alpine-chromium
          docker images
