name: Docker Hub Free

on:
  schedule:
    - cron: '3 2 1 */3 *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'GitCourser/docker'
    steps:
      - name: keep the activity
        env:
          user: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          REPOSITORIES=$(curl -s "https://hub.docker.com/v2/repositories/$user/" | jq -r '.results[] | .name')
          echo "$REPOSITORIES" | while read repo_name; do
            echo "Pulling $repo_name"
            docker pull -a $user/$repo_name
          done
          docker images
